/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by Next.js on first `next dev`/`next build`.
// It is committed here so a fresh checkout type-checks immediately.
